#!/usr/bin/env python3
"""Generate GOAL-9 scripts (XIANYX-171 to 230) by adapting GOAL-8 scripts.
Reads existing GOAL-8 scripts and creates adapted versions for episodes 31-40.
"""
import json, os, re, shutil
from pathlib import Path

ROOT = Path("C:/Users/PC/.paperclip/instances/default/workspaces/TKP_ACI")
IN_DIR = ROOT / "scripts" / "pending" / "xianxia"
OUT = ROOT / "scripts" / "pending" / "xianxia"
OUT.mkdir(parents=True, exist_ok=True)

# Series: (goal8_start, goal9_start, num_episodes, series_name, protagonist)
SERIES_MAP = [
    (111, 171, 10, "Ha Tien Du", "Luân", "fire-ice mastery, shadow empire, celestial realm, jade emperor, bridge"),
    (121, 181, 10, "Trieu Tien", "Xiao Yan", "dou di battleground, nine-star dou huang, flame sect, sky fortune saint, emperor"),
    (131, 191, 10, "Dau Pha Thuong Khau", "Xiao Yan and Xiao Mei", "flame emperor legacy, ninefold burning heaven, memory bridge, palace reborn, two halves"),
    (141, 201, 10, "Tru Tien", "Jeon Jin-Woo", "monarch of shadows, demon king absorbed, shadow throne, guardian not emperor, darkness protecting light"),
    (151, 211, 10, "Thanh Van Mon", "Nie Li", "time regression, demon dimension, sacred dragon, divine council, time master"),
    (161, 221, 10, "Muc Than Ky", "Mo Fan", "five elements, grand architect, forbidden archive, library creation, unification"),
]

# Episode arc templates for 31-40 (same for all series, adapted per series)
ARC_TEMPLATES_31_40 = [
    ("31", "The {series} Climax Begins", "The hero faces their greatest challenge yet — the culmination of everything they have learned.", "Challenge → Climax begins → Greatest test → Answer → Rising"),
    ("32", "The Power Peaks", "The hero reaches the absolute peak of their power — and must decide what to do with it.", "Peak power → Decision → Use it → Choice → Purpose"),
    ("33", "The Darkest Moment", "The darkest moment arrives — everything is lost. But in the darkness, the hero finds something unexpected.", "Darkest moment → Everything lost → In darkness → Unexpected → Hope"),
    ("34", "The Sacrifice Required", "A sacrifice is required — not of life, but of something more precious: identity, power, or belief.", "Sacrifice required → Precious choice → Identity/power/belief → Given up → Noble"),
    ("35", "The Final Stand", "The final stand — the hero confronts the ultimate threat with everything they have left.", "Final stand → Ultimate threat → Everything left → Confrontation → Heroism"),
    ("36", "The Transformation", "The hero transforms — not into something more powerful, but into something truer.", "Transformation → Not more power → Truer self → Achieved → Authentic"),
    ("37", "The Price Paid", "The price of the transformation is paid — and the hero must live with what it cost.", "Price paid → Cost revealed → Living with it → Acceptance → Peace"),
    ("38", "The World Changed", "The hero looks at the world they changed — and sees it was worth every sacrifice.", "World changed → Looking → Worth it → Every sacrifice → Justified"),
    ("39", "The Legacy Begins", "The hero begins passing their power and knowledge to the next generation.", "Legacy begins → Passing power → Next generation → Teaching → Hopeful"),
    ("40", "The Eternal {series} (Series Finale)", "The hero's story reaches its end — but what they built will last forever.", "Story ends → Built lasting → Eternal → Legend → Forever"),
]

# Series-specific arc overrides
SERIES_ARCS = {
    "Ha Tien Du": [
        ("31", "The Celestial Gate", "The celestial gate had been sealed since the first gods. Tonight, Luân carried the fire mark, ice mastery, and Water of Origin — and opened it alone.", "Gate → Three elements → Opens → Realm → Awe"),
        ("32", "The Celestial Library", "The celestial library held every secret of existence. Luân was given one hour — and chose a book of sacrifices over power techniques.", "Wonder → Offering → Choice → Sacrifice → Noble"),
        ("33", "The Road Home", "Luân descended from heaven carrying the knowledge of sacrifice. The shadow empire ambushed him with a thousand soldiers.", "Descent → Ambush → Alone fighting → Break through → Escape"),
        ("34", "The Last Gift", "Luân returned home to find shadow already there — his people trapped. He poured his elemental mastery into the barrier.", "Return → Horror → Pouring mastery → Sacrifice → Safe"),
        ("35", "The Last Bridge", "The bridge was almost gone. The void descended. And Luân — with nothing left — became the bridge one final time.", "Void → Nothing left → Bridge → Held → Eternal"),
        ("36", "The Eternal Water", "Luân became the eternal bridge between worlds. His body stretched across the void — became the barrier that would never fall.", "Bridge stretched → Void pressing → Will holding → Eternal → Protected"),
        ("37", "The Final Trial", "The celestial realm sent its final trial: not combat — but the choice to let go and become mortal again.", "Trial → Choice → Let go → Mortal → Freedom"),
        ("38", "The Mortal Return", "Luân returned to the mortal realm — no fire mark, no ice blades. Just a man. And his people — safe forever.", "Mortal return → No powers → Just a man → Safe → Peace"),
        ("39", "The Water Remembers", "Years later: the waterfall glowed. Luân — old now — sat beside it. And the water showed him everyone he had saved.", "Years later → Old → Water shows → Saved lives → Gratitude"),
        ("40", "The Eternal Spring (Finale)", "On his last day, Luân returned to the dragon gate. Heaven itself — bowed to the mortal who had become eternal.", "Last day → Dragon gate → Heaven bows → Mortal eternal → Legend"),
    ],
    "Trieu Tien": [
        ("31", "The Nine-Star Summit", "The Dou Di Summit: nine Nine-star Dou Huangs gathered. Xiao Yan — the youngest — was the only one who earned his stars through failure.", "Gathering → Youngest → Failure earned → Dominance → Proof"),
        ("32", "The Flame Sect's Legacy", "The Flame Sect elders revealed: the Extinction Flame was not just a technique — it was a philosophy. To burn the old — so the new could be born.", "Legacy → Philosophy → Burn old → New born → Understanding"),
        ("33", "The Dou Zong Challenge", "A Dou Zong — two full realms above — challenged Xiao Yan publicly. He accepted — and showed why technique beats raw power.", "Challenge → Accept → Technique vs power → Victory → Proof"),
        ("34", "The Sky Fortune Saint's Test", "The Sky Fortune Saint tested Xiao Yan with a question: 'What will you burn to build your world?'", "Test → Question → What to burn → Answer → Purpose"),
        ("35", "The Emperor's Decree", "Xiao Yan became the youngest Flame Emperor in history — not by conquest, but by asking his people what they needed.", "Becoming emperor → Asking → People's needs → New kind → Revolution"),
        ("36", "The Imperial Palace Fire", "Xiao Yan set fire to his own imperial palace — to prove that an emperor who could let go of comfort — could never be corrupted.", "Palace fire → Let go comfort → Cannot corrupt → Proof → Trust"),
        ("37", "The War of Philosophies", "Other empires attacked — not the body, but the philosophy. Xiao Yan's way threatened foundations of power everywhere.", "War → Philosophy attacked → Defense → New philosophy → Victory"),
        ("38", "The Flame Sect Reunites", "The Flame Sect — scattered for a thousand years — reunited under Xiao Yan. Not as army — as family.", "Reunion → Scattered → Family → Reunited → Strength"),
        ("39", "The Dou Di Congress", "Xiao Yan called the first Dou Di Congress — all realms, all factions. He proposed: no more wars fought over what could be shared.", "Congress → All realms → Sharing → Proposal → Beginning"),
        ("40", "The Eternal Flame (Finale)", "On his last day as emperor, Xiao Yan passed the Extinction Flame to the next generation — as a promise that burning old things — lets something better begin.", "Last day → Passing flame → Promise → New beginning → Eternal"),
    ],
    "Dau Pha Thuong Khau": [
        ("31", "The Emperor's Tomb Opens", "Xiao Mei touched the Emperor's tomb — and it opened. Inside: not a body — but the Flame Emperor's final lesson, preserved for a thousand years.", "Tomb opens → Not body → Final lesson → Preserved → Waiting"),
        ("32", "The Ninefold Complete", "Xiao Yan completed the Ninefold Burning Heaven — all nine transformations achieved. The Flame Emperor's full legacy — finally inherited.", "Ninefold complete → All nine → Full legacy → Inherited → Complete"),
        ("33", "The Memory Bridge", "Xiao Mei and Xiao Yan together became the memory bridge — connecting past emperor to future world. Two children — carrying a thousand years.", "Memory bridge → Two children → Past to future → Connected → Carrying"),
        ("34", "The Palace Reborn", "The Flame Emperor's palace — restored to its original glory — became not a tomb, but a living school where anyone could learn.", "Palace reborn → School not tomb → Living → Open → Learning"),
        ("35", "The Emperor's Two Halves", "The Flame Emperor had been two people who became one. Xiao Mei and Xiao Yan — proved that being two people who were one — was stronger.", "Two halves → Two who are one → Stronger → Proved → Complete"),
        ("36", "The Fire That Heals", "Xiao Yan discovered: the Extinction Flame could not only destroy — it could HEAL. Burn the sickness — not the body.", "Fire heals → Burn sickness → Revolutionary → Medicine → New way"),
        ("37", "The Academy Founded", "Xiao Yan founded the first Flame Academy — open to all, regardless of birth. The old world gasped. The new world began.", "Academy founded → Open to all → Old gasps → New begins → Beginning"),
        ("38", "The Betrayer's Redemption", "The disciple who had betrayed the Flame Emperor a thousand years ago — appeared. Not as enemy — as penitent.", "Betrayer appears → Penitent → Forgiveness → Redemption → Peace"),
        ("39", "The Eternal Fire", "The Flame Emperor's fire — now in two children — spread across the world. Not as conquest — as warmth.", "Eternal fire → Warmth not conquest → Every cold night lit → Warm → Everywhere"),
        ("40", "The Emperor's Children (Finale)", "The Flame Emperor watched from beyond — two children carrying his fire. And for the first time in a thousand years — he smiled.", "Emperor watching → Two children → Smile → Not restored — improved → Better"),
    ],
    "Tru Tien": [
        ("31", "The Shadow Throne's True Purpose", "Jeon Jin-Woo sat upon the shadow throne — and understood its true purpose: not to conquer light — but to protect it.", "Shadow throne → True purpose → Protect light → Guardian → Understood"),
        ("32", "The Monarch's Promise", "Jeon Jin-Woo made a promise: as long as he sat upon the shadow throne — no shadow would touch an innocent.", "Promise → Shadow throne → No innocent touched → Witnessed → Sacred"),
        ("33", "The Demon King Speaks", "The demon king within Jeon Jin-Woo spoke — not with malice, but with wisdom accumulated over ten thousand years.", "Demon king speaks → Not malice → Wisdom → Ten thousand years → Guidance"),
        ("34", "The Shadow Army Assembles", "Jeon Jin-Woo gathered shadow soldiers — not to attack, but to DEFEND. The largest protective army ever assembled.", "Shadow army → Assembles → Defend not attack → Largest protection → Unprecedented"),
        ("35", "The Darkest Realm's Invasion", "The darkest realm invaded — but found shadow armies protecting, not attacking. Confusion became fear became respect.", "Darkest realm → Invasion → Protection found → Confusion → Respect"),
        ("36", "The Monarch's Sacrifice", "Jeon Jin-Woo sacrificed his immortality — to become fully human again. The demon king's wisdom — would live in him as memory.", "Sacrifice → Immortality given up → Human again → Wisdom as memory → Living"),
        ("37", "The Peace Treaty", "Jeon Jin-Woo brokered the first peace treaty between light and shadow — not through weakness, but through understanding.", "Peace treaty → Light and shadow → Not weakness → Understanding → Historic"),
        ("38", "The Shadow Library", "Jeon Jin-Woo built the shadow library — every dark technique ever invented — with one purpose: so it could never be used again.", "Shadow library → Every dark technique → So it can't be used → Archive → Prevention"),
        ("39", "The Last Shadow Guard", "The last shadow guard was placed — not to keep enemies out, but to remind the world that darkness — was just light that had not yet found its way.", "Last shadow guard → Reminder → Darkness is light → Waiting → Hope"),
        ("40", "The Eternal Monarch (Finale)", "Jeon Jin-Woo left the shadow throne — and became the first mortal to walk freely between light and shadow — forever.", "Left throne → Freely walk → Between light and shadow → Forever → Eternal"),
    ],
    "Thanh Van Mon": [
        ("31", "The Divine Seal Cracks", "Glory City's divine seals — that had held for a thousand years — began to crack. Something ancient was about to return.", "Seals crack → Thousand years held → Ancient returning → About to happen → Urgent"),
        ("32", "The Demon Dimension Wakes", "The demon dimension stirred — and sent not an army, but a SINGLE MESSAGE: Nie Li. We remember. We are coming.", "Demon dimension wakes → Single message → We remember → Coming → Dread"),
        ("33", "The Time Master's Dilemma", "Nie Li discovered: sealing the demon dimension again would cost him everything — including the people he loved.", "Dilemma → Seal again → Cost everything → Including loved ones → Heartbreaking"),
        ("34", "The Past Life War", "Nie Li's past life memories flooded back — a war that had lasted a thousand years — and he was the one who had started it.", "Past life war → Thousand years → He started it → Guilt → Understanding"),
        ("35", "The God Realm Intervention", "The god realm intervened — and offered Nie Li godhood in exchange for opening the demon dimension willingly.", "God realm → Intervention → Godhood offered → Exchange → Temptation"),
        ("36", "The Time Regression Reborn", "Nie Li used time regression not to go back — but to bring the future forward. Every sacrifice that would happen — he saw. And changed.", "Regression reborn → Future brought forward → Every sacrifice seen → Changed → Redeemed"),
        ("37", "The Sacred Dragon's Final Gift", "The sacred dragon — dying — gave Nie Li its final gift: the ability to see time — not as a line, but as a web.", "Dragon's final gift → See time as web → Not line → Connected → Wisdom"),
        ("38", "The Demon King's Apology", "The demon king — appearing in person — apologized. 'We did not know what we were doing. We were young.'", "Demon king apology → Appearing → Did not know → Young → Understanding"),
        ("39", "The Web of Time", "Nie Li wove the web of time — connecting every realm, every era, every choice — into one infinite tapestry of existence.", "Web of time → Every realm → Every era → One tapestry → Infinite"),
        ("40", "The Eternal Time (Finale)", "Nie Li became one with time itself — not as a god, but as the flow between moments. Every hero's story — carried forward.", "One with time → Not god → Flow between moments → Every story → Carried"),
    ],
    "Muc Than Ky": [
        ("31", "The Forbidden Floor Opens", "The forbidden floor's final door — the one that had never been opened — creaked. Mo Fan stood before it with all five elements mastered.", "Forbidden floor → Final door → Never opened → Stood before → Destiny"),
        ("32", "The Five Elements Speak", "The five elements spoke — for the first time in ten thousand years. They had been waiting for someone who could truly listen.", "Five elements speak → Ten thousand years → Waiting → Listen → Connection"),
        ("33", "The Grand Architect's Memory", "Mo Fan remembered: he was not the reincarnation of the Grand Architect. He was the FIRST Grand Architect — who had forgotten.", "Architect's memory → Not reincarnation → Was first → Forgot → Remembered"),
        ("34", "The New World Takes Shape", "From his five-element palms — Mo Fan created not a weapon, not a technique — but the BLUEPRINT for a new world.", "New world → From five-element palms → Blueprint → Not weapon → Creation"),
        ("35", "The Library of Everything", "Mo Fan built the Library of Everything — every secret, every technique, every story — accessible to all who sought it.", "Library of everything → Every secret → Accessible to all → Seeking → Open"),
        ("36", "The Five Elements United", "The five elements united — not in Mo Fan's palms — but in every person who walked through the library's doors.", "Five elements united → Not in palms → In every person → Library doors → Everyone"),
        ("37", "The Student's Test", "A student — young, afraid, told she had no talent — walked through the library's doors. Mo Fan watched. And remembered himself.", "Student's test → Young, afraid → No talent → Walked through → Remembered"),
        ("38", "The Orphan's Library", "Mo Fan built the orphan's wing — for every child who had been told they were nothing. Every story of those who became something.", "Orphan's wing → Told nothing → Became something → Every story → Hope"),
        ("39", "The Grand Architect Returns", "Mo Fan returned to the place where he had been told he was nothing — and left a library. So no child would ever hear those words again.", "Grand architect returns → Told nothing → Left library → No child hears → Legacy"),
        ("40", "The Eternal Archive (Finale)", "Mo Fan faded — not in death, but in becoming the library itself. Every book, every secret, every story — was him now.", "Faded → Not death → Became library → Every book → Eternal"),
    ],
}

# Shot templates per series (reused for all 10 episodes)
SERIES_SHOTS = {
    "Ha Tien Du": [
        (0, "Extreme wide aerial — the celestial gate towering over the mortal realm. Luân standing before it, fire mark glowing on his forehead, ice blades crossed on his back, Water of Origin glowing in his palms. Three elements in one mortal.", "Extreme wide aerial — celestial gate, Luân with fire mark and ice blades, Water of Origin glowing, three elements united, 6s", "The celestial gate had been sealed since the first gods. And he — the mortal who had mastered fire, ice, and shadow — stood before it carrying everything he had learned.", "Celestial gate humming, fire mark sizzling, ice blades chiming, ancient power awakening, epic orchestral swell"),
        (6, "Wide cinematic — Luân combines fire and ice. Frost fire erupts around him — blue flames that burn cold. The most beautiful and deadly technique ever seen.", "Wide — frost fire erupting, blue flames dancing around Luân, fire and ice unified, most beautiful elemental technique, 6s", "Fire and ice. Two elements that had warred since the beginning of time. In his hands — they danced. And the dance was more beautiful than either could be alone.", "Frost fire erupting, ice crystals forming in flames, two elements singing together, beautiful power hum, ethereal orchestral"),
        (12, "Close-up — Luân faces a trial. A mirror of himself made of pure shadow. 'You could have been a god.' Luân: 'Gods are alone. Bridges are not.'", "Close-up — shadow mirror confronting Luân, profound choice declared, bridges vs gods, philosophical combat, 6s", "The shadow showed him what he could have been: a god. Eternal. Alone. And he chose — again — to be the bridge. Because bridges were never alone.", "Shadow mirror speaking, profound echo, his calm reply, philosophical tension, mystical strings"),
        (18, "Wide — the Jade Emperor's champion appears — to TEST. Five questions. Each harder than the last. Luân answers each — and ascends higher.", "Wide — Jade Emperor champion appearing, five questions test, Luân ascending higher with each answer, divine trial, 6s", "The five questions of heaven: What do you fight for? What do you die for? What do you live for? What do you become? And finally: Are you willing to let go?", "Champion appearing, divine question echoing, each answer reverberating, ascension sound, heaven responding"),
        (24, "Full-body cinematic — Luân stands at the peak. Heaven and earth meet at his feet. He raises both hands — fire, ice, and water merged into pure WHITE LIGHT. The celestial gate OPENS.", "Full-body cinematic — peak of heaven and earth, white light erupting from merged elements, celestial gate opening, transcendent peak, 6s", "He stood at the place where heaven and earth became one. And with fire, ice, and water unified — he opened the gate that had been closed since the first dawn.", "Gate opening grand sound, white light erupting, heaven and earth merging, divine orchestral crescendo, transcendent finale"),
    ],
    "Trieu Tien": [
        (0, "Extreme wide aerial — the Dou Di plains at sunrise. Thousands of cultivators gathered. In the center: Xiao Yan — Nine-star Dou Huang standing alone against an army of doubters.", "Extreme wide aerial — Dou Di plains at sunrise, thousands gathered, Xiao Yan alone at center, army of doubters, epic scale, 6s", "The Dou Di plains. Where emperors were made and pretenders were destroyed. And today — Xiao Yan would prove that a Nine-star Dou Huang was worth more than all of them combined.", "Crowd murmuring, doubters heckling, wind blowing across plains, epic tension, battle drums distant"),
        (6, "Close-up — Xiao Yan channels Nine-star Dou Huang power. Nine golden stars appear above his head — each one representing a breakthrough, a battle won, a loss transformed.", "Close-up — nine golden stars appearing above head, each star milestone, crowd gasping, Nine-star Dou Huang power fully revealed, 6s", "Nine stars. Nine breakthroughs. Nine times he had fallen and risen. And each star was not just power — it was proof that failure was just a lesson that took longer to learn.", "Stars igniting, breakthrough sound, crowd gasping, power revelation, golden light humming"),
        (12, "Wide cinematic — the Dou Di tournament begins. Xiao Yan faces opponent after opponent — each one stronger. He defeats them with the Extinction Flame — the fire that burned the old world.", "Wide cinematic — tournament battle, Extinction Flame defeating opponents one by one, dominant victory after victory, spectacular combat, 6s", "The Extinction Flame. The fire that had burned the old world and allowed a new one to be born. And he wielded it not to destroy — but to make space for something better.", "Extinction Flame roaring, opponents falling, tournament roar, dominant battle sounds, epic orchestral crescendo"),
        (18, "Close-up — the final opponent: a Dou Zong — two full realms above him. The Flame Sect protector speaks from within: 'It is not your power they need. It is your example.'", "Close-up — Dou Zong overwhelming him, despair moment, Flame Sect protector voice, example over power turning point, 6s", "He was outmatched. Completely. A Dou Zong was an emperor among mortals. But the protector whispered: power was not what they needed. His example was.", "Power overwhelming, despair silence, protector whisper, example sound, turning point orchestral"),
        (24, "Full-body cinematic — Xiao Yan channels the FULL Extinction Flame as a LIGHT. It illuminates the entire Dou Di plains. The Dou Zong shields his eyes. Xiao Yan wins — by BLINDING.", "Full-body cinematic — full Extinction Flame as blinding light, Dou Zong shielding eyes, unexpected victory by illumination not burning, 6s", "He won — not by being the strongest. But by being the most creative. The Extinction Flame could burn worlds. He used it to light a single moment so brightly — that even an emperor had to look away.", "Extinction Flame as brilliant light, Dou Zong shielding, unexpected victory sound, light spreading, triumphant orchestral finale"),
    ],
    "Dau Pha Thuong Khau": [
        (0, "Extreme wide aerial — the ancient ruins of the Flame Emperor's palace. Crumbling. Forgotten. Xiao Mei stands at the center with the Flame Emperor's memory burning in her mind.", "Extreme wide aerial — ancient Flame Emperor ruins, Xiao Mei alone at center, grandeur decayed, melancholic epic scale, 6s", "The Flame Emperor's palace had crumbled to dust — but the memories it held burned brighter than ever. And Xiao Mei — was the only one who remembered what it had been.", "Wind through ruins, dust settling, ancient grandeur silence, memory burning, melancholic orchestral swell"),
        (6, "Wide cinematic — Xiao Yan appears — not as cultivator, but as the Flame Emperor reborn. His body literally BLAZES with the Emperor's fire. The palace ruins RECOGNIZE him.", "Wide cinematic — Xiao Yan as Flame Emperor reborn, palace ruins recognizing true heir, emperor fire blazing, ancient recognition, 6s", "The palace had been waiting. For a thousand years — it had waited for the Flame Emperor to return. And tonight — in Xiao Yan's body — he finally did.", "Palace recognizing heir, emperor fire igniting, ancient recognition sound, fire roaring, destiny fulfilled orchestral"),
        (12, "Close-up — Xiao Mei and Xiao Yan stand together. The Flame Emperor's memories SPLIT between them — half for each. 'You are not rivals. You are the two halves of what I was.'", "Close-up — memories splitting between Xiao Yan and Xiao Mei, two halves revelation, Flame Emperor explaining purpose, profound truth moment, 6s", "The Flame Emperor had been two people before he became one. His fire — and his memory. And now — they were reunited in the only way they could be: two people who carried what he had been.", "Memories splitting sound, two halves reuniting, Flame Emperor voice, profound truth echo, emotional orchestral swell"),
        (18, "Wide — the Ninefold Burning Heaven technique is COMPLETE. Nine transformations. Each one burning away one weakness, one doubt, one limitation. Xiao Yan becomes PURE fire.", "Wide — Ninefold complete, nine weaknesses burned away, Xiao Yan becoming pure fire, nine transformations visible, peak power achieved, 6s", "Nine transformations. Nine weaknesses burned away. And what remained — was not a stronger version of who he had been. It was the first version of who he was always meant to become.", "Nine transformations sound, weaknesses burning away, pure fire achieved, nine flames dancing, peak power orchestral crescendo"),
        (24, "Full-body cinematic — Xiao Yan and Xiao Mei stand at the restored Flame Emperor palace — now BURNING with renewed life. The fire that had been dormant for a thousand years — blazed again.", "Full-body cinematic — restored Flame Emperor palace burning renewed, dormant fire blazing after thousand years, resurrection achieved, transcendent finale, 6s", "The Flame Emperor's palace burned again. Not with the fire of revenge — but with the fire of what came next. And two children stood at its center — carrying the weight of what had been — and the hope of what would be.", "Palace renewed fire blazing, thousand-year dormancy ending, resurrection sound, renewed hope orchestral, transcendent finale"),
    ],
    "Tru Tien": [
        (0, "Extreme wide aerial — the shadow throne room. Massive, dark, with a throne made of living shadow. Jeon Jin-Woo sits upon it — not as emperor — but as GUARDIAN.", "Extreme wide aerial — shadow throne room, throne of living shadow, Jeon Jin-Woo seated as guardian, dark grandeur, ominous scale, 6s", "The shadow throne. It could make him an emperor of darkness — or a guardian of light. He sat upon it — and chose: to be the bridge between shadow and light. Not to rule either.", "Shadow throne humming, living shadow breathing, guardian choice sound, dark grandeur, ominous orchestral"),
        (6, "Close-up — Jeon Jin-Woo faces his shadow self — the demon king that he had absorbed. 'We are one now. Not master and servant — but equals.' The demon king nods.", "Close-up — shadow self integration, demon king acknowledging partnership, equals not master and servant, profound unity, 6s", "The demon king had been his enemy. His greatest fear. And now — he was his most trusted partner. Because he had learned: our greatest fears — are often our greatest teachers.", "Shadow integration sound, demon king nod, equals partnership echo, profound unity orchestral, mystical swell"),
        (12, "Wide cinematic — Jeon Jin-Woo raises the shadow throne's power — and uses it NOT for conquest — but to PROTECT. Shadow walls rise around cities. Shadow soldiers defend the innocent.", "Wide cinematic — shadow power protecting not conquering, shadow walls defending cities, shadow soldiers as protectors, unprecedented use of dark power, 6s", "Shadow had always been used for conquest. For destruction. For fear. He turned it upside down — and used the darkest power in existence to protect. Because the best shield — was often the scariest thing on the battlefield.", "Shadow walls rising, protection sound, shadow soldiers defending, inverted purpose orchestral, heroic dark"),
        (18, "Close-up — the ancient demon armies ATTACK — but they ATTACK SHADOW SOLDIERS. Jeon Jin-Woo watches from the shadow throne as his shadow army defends his world.", "Close-up — ancient demons attacking shadow army, Jeon Jin-Woo watching from throne, shadow army defending, profound statement about shadow's purpose, 6s", "The ancient demons had come to conquer. And they found shadow — the thing they thought was their ally — standing in their way. Turned. By the one man who understood darkness better than any of them.", "Ancient demons attacking, shadow army defending, Jeon Jin-Woo watching, profound shadow purpose statement, battle orchestral"),
        (24, "Full-body cinematic — Jeon Jin-Woo descends from the shadow throne — not as emperor, but as the MONARCH OF SHADOWS. The one who controlled darkness — so that light could survive.", "Full-body cinematic — descent as Monarch of Shadows, darkness serving light, guardian not emperor, shadow throne transforming to protective symbol, transcendent finale, 6s", "He was not the emperor of shadow. He was the monarch of it — which meant he understood it completely. And what he understood most — was that the scariest darkness — was always the best guardian of the light.", "Descent sound, monarch title declared, shadow transforming from conquest to protection, guardian achieved, transcendent orchestral finale"),
    ],
    "Thanh Van Mon": [
        (0, "Extreme wide aerial — Glory City at dawn. Sacred Dragon Sect's ancient seals — that had held for a thousand years — begin to CRACK. Something ancient stirs beneath.", "Extreme wide aerial — Glory City at dawn, dragon seals cracking after thousand years, something ancient stirring, ominous epic scale, 6s", "The dragon seals had held — through wars, through dynasties, through the slow forgetting of an age. But time was finding its way through. And what slumbered beneath — was beginning to wake.", "Seals cracking, ancient stirring, thousand-year sleep ending, ominous rumble, epic orchestral swell"),
        (6, "Close-up — Nie Li in the sacred archive. Reading the time regression scrolls. He discovers: the demon dimension had been sealed by HIS OWN CHOICE — in a past life.", "Close-up — sacred archive, time regression scrolls revealing truth, Nie Li discovers past life choice sealed demon dimension, shocking revelation, 6s", "He had sealed the demon dimension. Not a god. Not an ancient hero. Him — in a life he did not remember. And now — he would have to decide whether to seal it again — or let the past decision stand.", "Scroll revealing, past life echoing, shocking truth discovered, time regression hum, revelation orchestral swell"),
        (12, "Wide cinematic — the demon dimension gate CRACKS OPEN. Black chaos pours through — not an army, but PURE DARK INTENT. It seeks one thing: Nie Li. The one who had imprisoned it.", "Wide cinematic — demon gate cracking, chaos pouring through, dark intent seeking Nie Li specifically, terrifying scale, 6s", "The demon dimension did not send an army. It sent INTENTION. Pure, focused, ancient malice that had been waiting a thousand years for one target: the man who had locked the door.", "Gate cracking, chaos pouring, ancient malice targeting, terrifying silence before attack, ominous orchestral crescendo"),
        (18, "Close-up — Nie Li stands before the gate. He has three choices: reseal it (lose his powers forever), fight it (probably die), or TRANSFORM it. He chooses the third.", "Close-up — three choices presented, transformation chosen over sealing or fighting, Nie Li's decisive expression, profound decision, 6s", "Seal it — and become mortal. Fight it — and probably lose. Transform it — and risk everything. He chose the third. Because the only thing scarier than an ancient demon dimension — was a time master with nothing left to lose.", "Three choices appearing, transformation choice, decisive sound, ancient risk accepted, daring orchestral"),
        (24, "Full-body cinematic — Nie Li reaches into the demon dimension — and REWINDS it. Not fighting it — REVERSING it. The chaos flows BACKWARD. The gate seals from inside.", "Full-body cinematic — reaching into demon dimension, rewinding chaos backward, gate sealing from inside out, impossible reversal, transcendent finale, 6s", "He did not fight the demon dimension. He simply — reversed it. And in reversing ten thousand years of malice — he proved that time — was stronger than hate.", "Rewind sound, chaos reversing, gate sealing from inside, time triumphing over hate, transcendent orchestral finale"),
    ],
    "Muc Than Ky": [
        (0, "Extreme wide aerial — the Grand Library's forbidden floor. Five elemental doors — fire, water, earth, wind, thunder — now OPEN. All five at once. Mo Fan walks through all of them simultaneously.", "Extreme wide aerial — all five elemental doors open simultaneously, Mo Fan walking through all at once, unprecedented event, 6s", "The five elemental doors had been opened one at a time for ten thousand years. Today — Mo Fan opened all five simultaneously. Because true mastery was not about choosing one element — it was about unifying them.", "Five doors opening simultaneously, unprecedented event, elemental hum, his steady footsteps, epic orchestral swell"),
        (6, "Wide cinematic — Mo Fan combines all five elements for the FIRST TIME IN HISTORY. Fire, water, earth, wind, thunder — MERGE in his five-element palms. Not five powers — ONE power.", "Wide cinematic — five elements merging in five-element palms, one unified power achieved, first time in history, unprecedented power, 6s", "Five elements. Ten thousand years of separation. In his palms — they became one. Not because he forced them — but because he finally understood what each of them had always been trying to become.", "Five elements merging, unified power humming, first time in history, harmony achieved, unprecedented orchestral swell"),
        (12, "Close-up — the Grand Architect's COMPLETE HISTORY appears in the library's light. Mo Fan sees: he IS the first Grand Architect. Not reborn — REMEMBERED. He always was.", "Close-up — Grand Architect complete history appearing, complete truth revealed, Mo Fan always was first Architect, shocking full revelation, 6s", "He was not the reincarnation of the Grand Architect. He was not a copy. He was not a successor. He WAS the first Grand Architect — who had simply forgotten — and was now remembering.", "History fully revealing, complete truth echoing, realization dawning, first Architect confirmed, revelation orchestral swell"),
        (18, "Wide — Mo Fan creates from his five-element palms — not a